# Generated by Django 5.2.4 on 2025-07-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_data_todo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
